import type { Language } from '../../content';

export const arcadeCopy = {
  pt: {
    mode: 'Modo arcade',
    headline: 'Caio Massola',
    role: 'Engenheiro de software frontend',
    choose: 'Escolha o jogo',
    play: 'Jogar',
    runner: 'Capivara Run',
    snake: 'Cobrinha',
    blocks: 'Blocos',
    runnerDesc: 'Pule. Desvie. Bata seu recorde.',
    snakeDesc: 'Só mais uma maçã.',
    blocksDesc: 'Encaixe e complete as linhas.',
    tic: 'Jogo da velha',
    ticDesc: 'Três em linha. Sua próxima jogada?',
    memoryDesc: '12 pares. Encontre todos.',
    memory: 'Memória',
    score: 'Pontos',
    best: 'Recorde',
    start: 'Começar',
    pause: 'Pausar',
    resume: 'Continuar',
    restart: 'Recomeçar',
    close: 'Sair do jogo',
    ready: 'Tudo pronto?',
    paused: 'Jogo pausado',
    over: 'Fim de jogo',
    jump: 'Pular',
    left: 'Esquerda',
    right: 'Direita',
    up: 'Cima',
    down: 'Baixo',
    rotate: 'Girar',
    drop: 'Soltar',
    runnerHelp: 'Espaço, ↑ ou toque em Pular. Desvie dos obstáculos.',
    snakeHelp: 'Setas ou WASD para mover. Coma as maçãs sem bater.',
    blocksHelp: '← → movem · ↑ gira · ↓ desce · espaço solta.',
    pauseHelp: 'P pausa · Esc sai',
    projects: 'Ver projetos',
  },
  en: {
    mode: 'Arcade mode',
    headline: 'Caio Massola',
    role: 'Frontend software engineer',
    choose: 'Choose your game',
    play: 'Play',
    runner: 'Capybara Run',
    snake: 'Snake',
    blocks: 'Blocks',
    runnerDesc: 'Jump. Dodge. Beat your best.',
    snakeDesc: 'Just one more apple.',
    blocksDesc: 'Stack blocks. Clear the lines.',
    tic: 'Tic tac toe',
    ticDesc: 'Three in a row. Your next move?',
    memoryDesc: '12 pairs. Find them all.',
    memory: 'Memory',
    score: 'Score',
    best: 'Best',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    restart: 'Restart',
    close: 'Exit game',
    ready: 'Ready?',
    paused: 'Game paused',
    over: 'Game over',
    jump: 'Jump',
    left: 'Left',
    right: 'Right',
    up: 'Up',
    down: 'Down',
    rotate: 'Rotate',
    drop: 'Drop',
    runnerHelp: 'Space, ↑ or tap Jump. Avoid the obstacles.',
    snakeHelp: 'Arrow keys or WASD to move. Eat apples without crashing.',
    blocksHelp: '← → move · ↑ rotate · ↓ down · space drop.',
    pauseHelp: 'P pauses · Esc exits',
    projects: 'View projects',
  },
  es: {
    mode: 'Modo arcade',
    headline: 'Caio Massola',
    role: 'Ingeniero de software frontend',
    choose: 'Elige tu juego',
    play: 'Jugar',
    runner: 'Capibara Run',
    snake: 'Serpiente',
    blocks: 'Bloques',
    runnerDesc: 'Salta. Esquiva. Supera tu récord.',
    snakeDesc: 'Solo una manzana más.',
    blocksDesc: 'Encaja y completa las líneas.',
    tic: 'Tres en raya',
    ticDesc: 'Tres en línea. ¿Tu siguiente jugada?',
    memoryDesc: '12 parejas. Encuéntralas todas.',
    memory: 'Memoria',
    score: 'Puntos',
    best: 'Récord',
    start: 'Empezar',
    pause: 'Pausar',
    resume: 'Continuar',
    restart: 'Reiniciar',
    close: 'Salir del juego',
    ready: '¿Todo listo?',
    paused: 'Juego en pausa',
    over: 'Fin del juego',
    jump: 'Saltar',
    left: 'Izquierda',
    right: 'Derecha',
    up: 'Arriba',
    down: 'Abajo',
    rotate: 'Girar',
    drop: 'Soltar',
    runnerHelp: 'Espacio, ↑ o toca Saltar. Evita los obstáculos.',
    snakeHelp: 'Flechas o WASD para moverte. Come sin chocar.',
    blocksHelp: '← → mueven · ↑ gira · ↓ baja · espacio suelta.',
    pauseHelp: 'P pausa · Esc sale',
    projects: 'Ver proyectos',
  },
} satisfies Record<Language, Record<string, string>>;
