export const portfolioCopy = {
  pt: {
    player: 'PLAYER 01 / SOBRE',
    about: 'Quem está no controle',
    intro:
      'Sou o Caio. Meu trabalho é transformar requisitos em interfaces que as pessoas conseguem usar.',
    bio: 'Atuo no front-end, mas também já passei por APIs, bancos de dados e aplicativos mobile. Aqui, os jogos dividem espaço com projetos e experiências reais de desenvolvimento.',
    role: 'Classe: engenheiro front-end',
    experience: '6+ anos em web e mobile',
    education: 'Formação desbloqueada',
    kit: 'INVENTÁRIO / TECNOLOGIAS',
    kitTitle: 'Escolha um conjunto',
    kitIntro:
      'Cada parte do projeto pede ferramentas diferentes. Explore o que uso em cada etapa.',
    groups: ['Interfaces', 'Qualidade', 'Serviços'],
    groupText: [
      'Do navegador ao celular: telas, componentes e comunicação com APIs.',
      'Testes para conferir o comportamento e Storybook para documentar componentes.',
      'O que conecta a interface aos dados, às integrações e ao ambiente de execução.',
    ],
    career: 'CAMPANHA / EXPERIÊNCIA',
    careerTitle: 'Fases da minha carreira',
    careerIntro:
      'Do primeiro contato com código em produção ao desenvolvimento de um produto corporativo.',
    stage: 'FASE',
    current: 'EM ANDAMENTO',
    careerNotes: [
      'Angular, TypeScript e Node.js no dia a dia: integrar APIs, corrigir bugs e aprender com o time.',
      'O escopo cresceu: web com Angular, serviços com Node.js e MySQL, além de apps com React Native.',
      'Hoje, o foco está no front-end de um produto corporativo: React, TypeScript, componentes, testes e Design System.',
    ],
    projects: 'SELEÇÃO / PROJETOS',
    projectsTitle: 'Escolha um projeto',
    projectsIntro: 'Jogos, uma API e um bot. Selecione um para ver o que construí.',
    objective: 'O DESAFIO',
    projectNotes: [
      'Levar o jogo da velha para uma sala online, com chat e partidas em tempo real.',
      'Manter as regras da partida no servidor e sincronizar os dois jogadores.',
      'Transformar o reconhecimento de campeões de League of Legends em um desafio visual rápido.',
      'Explorar física e multiplayer em um jogo 3D de futebol com carros, inspirado em Rocket League.',
      'Acompanhar preços e histórico e enviar ofertas ao Discord, com Java, Spring Boot e Docker.',
    ],
    open: 'Abrir projeto',
    source: 'Ver código',
    sourceOnly: 'Disponível no GitHub',
    contact: 'MODO COOPERATIVO / CONTATO',
    contactTitle: 'Vamos construir juntos?',
    contactText:
      'Tem uma oportunidade ou um projeto para conversar? Escolha um canal e me conte a ideia.',
    chat: 'Chamar no WhatsApp',
    mail: 'Mandar e-mail',
    again: 'Voltar aos jogos',
    footer: 'FIM DA FASE. A CONVERSA CONTINUA.',
    cv: 'Baixar currículo',
  },
  en: {
    player: 'PLAYER 01 / ABOUT',
    about: 'Behind the controls',
    intro: 'I’m Caio. My work is turning requirements into interfaces people can use.',
    bio: 'I work in front-end, with experience in APIs, databases and mobile apps too. Here, games sit alongside real projects and development experience.',
    role: 'Class: front-end engineer',
    experience: '6+ years in web and mobile',
    education: 'Education unlocked',
    kit: 'INVENTORY / TECHNOLOGIES',
    kitTitle: 'Choose a toolkit',
    kitIntro:
      'Different parts of a project need different tools. Explore what I use at each step.',
    groups: ['Interfaces', 'Quality', 'Services'],
    groupText: [
      'From browser to phone: screens, components and API communication.',
      'Tests to check behavior and Storybook to document components.',
      'Connecting interfaces to data, integrations and runtime environments.',
    ],
    career: 'CAMPAIGN / EXPERIENCE',
    careerTitle: 'My career stages',
    careerIntro: 'From my first production code to building an enterprise product.',
    stage: 'STAGE',
    current: 'IN PROGRESS',
    careerNotes: [
      'Angular, TypeScript and Node.js: integrating APIs, fixing bugs and learning with the team.',
      'A wider scope: Angular web apps, Node.js and MySQL services, and React Native apps.',
      'Today I focus on an enterprise front-end: React, TypeScript, components, tests and a Design System.',
    ],
    projects: 'SELECT / PROJECTS',
    projectsTitle: 'Choose a project',
    projectsIntro: 'Games, an API and a bot. Select one to explore what I built.',
    objective: 'THE CHALLENGE',
    projectNotes: [
      'Bring tic-tac-toe to online rooms with chat and real-time matches.',
      'Keep match rules on the server and synchronize both players.',
      'Turn League of Legends champion recognition into a fast visual challenge.',
      'Explore physics and multiplayer in a Java 3D car soccer game inspired by Rocket League.',
      'Track prices and history and send deals to Discord with Java, Spring Boot and Docker.',
    ],
    open: 'Open project',
    source: 'View code',
    sourceOnly: 'Available on GitHub',
    contact: 'CO-OP MODE / CONTACT',
    contactTitle: 'Let’s build together.',
    contactText:
      'Have an opportunity or a project to discuss? Choose a channel and tell me about it.',
    chat: 'Chat on WhatsApp',
    mail: 'Send an email',
    again: 'Back to the games',
    footer: 'STAGE COMPLETE. LET’S KEEP TALKING.',
    cv: 'Download résumé',
  },
  es: {
    player: 'PLAYER 01 / SOBRE MÍ',
    about: 'Detrás de los controles',
    intro:
      'Soy Caio. Mi trabajo es convertir requisitos en interfaces que las personas puedan usar.',
    bio: 'Trabajo en front-end y también tengo experiencia con APIs, bases de datos y aplicaciones móviles. Aquí los juegos comparten espacio con proyectos y experiencias reales de desarrollo.',
    role: 'Clase: ingeniero front-end',
    experience: '6+ años en web y móvil',
    education: 'Formación desbloqueada',
    kit: 'INVENTARIO / TECNOLOGÍAS',
    kitTitle: 'Elige tus herramientas',
    kitIntro:
      'Cada parte del proyecto necesita herramientas diferentes. Explora lo que uso en cada etapa.',
    groups: ['Interfaces', 'Calidad', 'Servicios'],
    groupText: [
      'Del navegador al móvil: pantallas, componentes y comunicación con APIs.',
      'Pruebas de comportamiento y Storybook para documentar componentes.',
      'Conexión entre interfaces, datos, integraciones y entornos de ejecución.',
    ],
    career: 'CAMPAÑA / EXPERIENCIA',
    careerTitle: 'Etapas de mi carrera',
    careerIntro:
      'Del primer código en producción al desarrollo de un producto empresarial.',
    stage: 'ETAPA',
    current: 'EN CURSO',
    careerNotes: [
      'Angular, TypeScript y Node.js: integrar APIs, corregir errores y aprender con el equipo.',
      'Un alcance mayor: web con Angular, servicios con Node.js y MySQL y apps con React Native.',
      'Hoy me centro en un front-end empresarial: React, TypeScript, componentes, pruebas y Design System.',
    ],
    projects: 'SELECCIÓN / PROYECTOS',
    projectsTitle: 'Elige un proyecto',
    projectsIntro: 'Juegos, una API y un bot. Selecciona uno para ver lo que construí.',
    objective: 'EL DESAFÍO',
    projectNotes: [
      'Llevar tres en raya a salas online con chat y partidas en tiempo real.',
      'Mantener las reglas en el servidor y sincronizar a ambos jugadores.',
      'Convertir el reconocimiento de campeones de League of Legends en un desafío visual rápido.',
      'Explorar física y multijugador en un juego 3D en Java de fútbol con coches, inspirado en Rocket League.',
      'Seguir precios e historial y enviar ofertas a Discord con Java, Spring Boot y Docker.',
    ],
    open: 'Abrir proyecto',
    source: 'Ver código',
    sourceOnly: 'Disponible en GitHub',
    contact: 'MODO COOPERATIVO / CONTACTO',
    contactTitle: '¿Construimos juntos?',
    contactText:
      '¿Tienes una oportunidad o un proyecto? Elige un canal y cuéntame tu idea.',
    chat: 'Hablar por WhatsApp',
    mail: 'Enviar un correo',
    again: 'Volver a los juegos',
    footer: 'ETAPA COMPLETADA. SIGAMOS HABLANDO.',
    cv: 'Descargar currículum',
  },
};
